name: Auto Comment

on: [issues]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            #### 📖 Commands on ChatOps
            > | Command            | Description 
            > | ------------------ | -------------------------------------------- 
            > | `.provision <env>` | Provision current issue on an infrastructure. <br/> Environments: <br/> - development <br/> - feature
