name: Chat Ops

on:
  issue_comment:
    types: [ created ]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: 👋 ChatOps
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: NejcZdovc/comment-pr@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          message: |
            > 📖 Commands on ChatOps
            > Command | Description
            > --- | ---
            > /hello-world | Receive a greeting
