name: Help Command
on:
  repository_dispatch:
    types: [ help-command ]
jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - name: 🤖 Bot comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
          body: |
            #### 📖 Actions on ChatOps
            > | Actions            | Description 
            > | ------------------ | -------------------------------------------- 
            > | `.provision <env>` | Provision current issue on an infrastructure. <br/> Environments: <br/> - development <br/> - feature